FROM python:3.11-slim
ARG PIP_INDEX_URL=https://pypi.org/simple
WORKDIR /app
RUN pip install --no-cache-dir --index-url $PIP_INDEX_URL paho-mqtt
COPY infra/mqtt_publisher/publisher.py /app/publisher.py
CMD ["python", "publisher.py"]
