FROM python:3.11-slim
ARG PIP_INDEX_URL=https://pypi.org/simple
WORKDIR /app
RUN pip install --no-cache-dir --index-url $PIP_INDEX_URL asyncua
COPY infra/opcua_server/server.py /app/server.py
EXPOSE 4840
CMD ["python", "server.py"]
